# Change these first
owner: teamgreyfinch # Your GitHub organization or username, where this repository lives
repo: staging-status # The name of this repository

sites:
  - name: PMS Application - https://app.staging.greyfinch.com/
    url: https://app.staging.greyfinch.com/
  - name: Admin/Comms App - https://admin.staging.greyfinch.com/
    url: https://admin.staging.greyfinch.com/
  - name: Patient Hub - https://hub.staging.greyfinch.com/
    url: https://hub.staging.greyfinch.com/
  - name: Appointments Widget
    url: https://appointments.staging.greyfinch.com/?division=981581
    icon: https://raw.githubusercontent.com/teamgreyfinch/public-status/master/assets/cropped-favgreen-01-1-192x192.png
  - name: API
    url: https://api.staging.greyfinch.com/healthz
    icon: https://raw.githubusercontent.com/teamgreyfinch/public-status/master/assets/cropped-favgreen-01-1-192x192.png
    __dangerous__body_down: WARN

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /staging-status
  logoUrl: https://raw.githubusercontent.com/teamgreyfinch/public-status/master/assets/cropped-favgreen-01-1-192x192.png
  favicon: https://raw.githubusercontent.com/teamgreyfinch/public-status/master/assets/cropped-favgreen-01-1-192x192.png
  robotsText: "User-agent: * \n Disallow: /"
  name:  Greyfinch Staging
  introTitle: "Greyfinch Uptime and Status Monitor"
  introMessage: Realtime status monitoring of Greyfinch applications
  navbar:
    - title: Production
      href: https://teamgreyfinch.github.io/public-status/
    - title: Staging
      href: https://teamgreyfinch.github.io/staging-status/
    - title: Demo
      href: https://teamgreyfinch.github.io/demo-status/

i18n:
  footer: Powered by [Upptime](https://upptime.js.org) 
  #   - title: GitHub
  #     href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
